// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "mlkit_frameworks",
    platforms: [
        .iOS("15.5")
    ],
    products: [
        .library(name: "MLKitBarcodeScanning", targets: ["MLKitBarcodeScanning"]),
        .library(name: "MLKitCommon", targets: ["MLKitCommon"]),
        .library(name: "MLKitDigitalInkRecognition", targets: ["MLKitDigitalInkRecognition"]),
        .library(name: "MLKitEntityExtraction", targets: ["MLKitEntityExtraction"]),
        .library(name: "MLKitFaceDetection", targets: ["MLKitFaceDetection"]),
        .library(name: "MLKitImageLabeling", targets: ["MLKitImageLabeling"]),
        .library(name: "MLKitImageLabelingCommon", targets: ["MLKitImageLabelingCommon"]),
        .library(name: "MLKitImageLabelingCustom", targets: ["MLKitImageLabelingCustom"]),
        .library(name: "MLKitLanguageID", targets: ["MLKitLanguageID"]),
        .library(name: "MLKitLinkFirebase", targets: ["MLKitLinkFirebase"]),
        .library(name: "MLKitObjectDetection", targets: ["MLKitObjectDetection"]),
        .library(name: "MLKitObjectDetectionCommon", targets: ["MLKitObjectDetectionCommon"]),
        .library(name: "MLKitObjectDetectionCustom", targets: ["MLKitObjectDetectionCustom"]),
        .library(name: "MLKitPoseDetection", targets: ["MLKitPoseDetection"]),
        .library(name: "MLKitPoseDetectionAccurate", targets: ["MLKitPoseDetectionAccurate"]),
        .library(name: "MLKitPoseDetectionCommon", targets: ["MLKitPoseDetectionCommon"]),
        .library(name: "MLKitSegmentationCommon", targets: ["MLKitSegmentationCommon"]),
        .library(name: "MLKitSegmentationSelfie", targets: ["MLKitSegmentationSelfie"]),
        .library(name: "MLKitSmartReply", targets: ["MLKitSmartReply"]),
        .library(name: "MLKitTextRecognition", targets: ["MLKitTextRecognition"]),
        .library(name: "MLKitTextRecognitionCommon", targets: ["MLKitTextRecognitionCommon"]),
        .library(name: "MLKitTextRecognitionChinese", targets: ["MLKitTextRecognitionChinese"]),
        .library(name: "MLKitTextRecognitionDevanagari", targets: ["MLKitTextRecognitionDevanagari"]),
        .library(name: "MLKitTextRecognitionJapanese", targets: ["MLKitTextRecognitionJapanese"]),
        .library(name: "MLKitTextRecognitionKorean", targets: ["MLKitTextRecognitionKorean"]),
        .library(name: "MLKitTranslate", targets: ["MLKitTranslate"]),
        .library(name: "MLKitVision", targets: ["MLKitVision"]),
        .library(name: "MLKitVisionKit", targets: ["MLKitVisionKit"]),
        .library(name: "MLKitXenoCommon", targets: ["MLKitXenoCommon"]),
    ],
    targets: [
        .binaryTarget(name: "MLKitBarcodeScanning", path: "Frameworks/MLKitBarcodeScanning.xcframework"),
        .binaryTarget(name: "MLKitCommon", path: "Frameworks/MLKitCommon.xcframework"),
        .binaryTarget(name: "MLKitDigitalInkRecognition", path: "Frameworks/MLKitDigitalInkRecognition.xcframework"),
        .binaryTarget(name: "MLKitEntityExtraction", path: "Frameworks/MLKitEntityExtraction.xcframework"),
        .binaryTarget(name: "MLKitFaceDetection", path: "Frameworks/MLKitFaceDetection.xcframework"),
        .binaryTarget(name: "MLKitImageLabeling", path: "Frameworks/MLKitImageLabeling.xcframework"),
        .binaryTarget(name: "MLKitImageLabelingCommon", path: "Frameworks/MLKitImageLabelingCommon.xcframework"),
        .binaryTarget(name: "MLKitImageLabelingCustom", path: "Frameworks/MLKitImageLabelingCustom.xcframework"),
        .binaryTarget(name: "MLKitLanguageID", path: "Frameworks/MLKitLanguageID.xcframework"),
        .binaryTarget(name: "MLKitLinkFirebase", path: "Frameworks/MLKitLinkFirebase.xcframework"),
        .binaryTarget(name: "MLKitObjectDetection", path: "Frameworks/MLKitObjectDetection.xcframework"),
        .binaryTarget(name: "MLKitObjectDetectionCommon", path: "Frameworks/MLKitObjectDetectionCommon.xcframework"),
        .binaryTarget(name: "MLKitObjectDetectionCustom", path: "Frameworks/MLKitObjectDetectionCustom.xcframework"),
        .binaryTarget(name: "MLKitPoseDetection", path: "Frameworks/MLKitPoseDetection.xcframework"),
        .binaryTarget(name: "MLKitPoseDetectionAccurate", path: "Frameworks/MLKitPoseDetectionAccurate.xcframework"),
        .binaryTarget(name: "MLKitPoseDetectionCommon", path: "Frameworks/MLKitPoseDetectionCommon.xcframework"),
        .binaryTarget(name: "MLKitSegmentationCommon", path: "Frameworks/MLKitSegmentationCommon.xcframework"),
        .binaryTarget(name: "MLKitSegmentationSelfie", path: "Frameworks/MLKitSegmentationSelfie.xcframework"),
        .binaryTarget(name: "MLKitSmartReply", path: "Frameworks/MLKitSmartReply.xcframework"),
        .binaryTarget(name: "MLKitTextRecognition", path: "Frameworks/MLKitTextRecognition.xcframework"),
        .binaryTarget(name: "MLKitTextRecognitionCommon", path: "Frameworks/MLKitTextRecognitionCommon.xcframework"),
        .binaryTarget(name: "MLKitTextRecognitionChinese", path: "Frameworks/MLKitTextRecognitionChinese.xcframework"),
        .binaryTarget(name: "MLKitTextRecognitionDevanagari", path: "Frameworks/MLKitTextRecognitionDevanagari.xcframework"),
        .binaryTarget(name: "MLKitTextRecognitionJapanese", path: "Frameworks/MLKitTextRecognitionJapanese.xcframework"),
        .binaryTarget(name: "MLKitTextRecognitionKorean", path: "Frameworks/MLKitTextRecognitionKorean.xcframework"),
        .binaryTarget(name: "MLKitTranslate", path: "Frameworks/MLKitTranslate.xcframework"),
        .binaryTarget(name: "MLKitVision", path: "Frameworks/MLKitVision.xcframework"),
        .binaryTarget(name: "MLKitVisionKit", path: "Frameworks/MLKitVisionKit.xcframework"),
        .binaryTarget(name: "MLKitXenoCommon", path: "Frameworks/MLKitXenoCommon.xcframework"),
    ]
)
